name: Feature request
description: Request an enhancement for iNook
labels: [enhancement]
body:

  - type: markdown
    attributes:
      value: |
        Before requesting: search [existing feature requests](https://github.com/jeluchu/inook-releases/labels/enhancement).

  - type: textarea
    attributes:
      label: "Problem"
      description: "Describe the problem to be solved."
      placeholder: "No bells available. Bells are important because..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe what the new feature or behavior would look like. How does it solve the problem?"
    validations:
      required: true